config/routes.rb
Rails.application.routes.draw do

  # Administorator device
  devise_for :administrators, :path => "administrators", :path_names => {
      :sign_in => 'login',
      :sign_out => 'logout',
      :password => 'secret',
      :confirmation => 'verification',
      :unlock => 'unblock',
      :registration => 'register',
      :sign_up => 'singup'
  }, :controllers => {
      :sessions => 'administrators/sessions',
      :passwords => 'administrators/passwords',
      :registrations => 'administrators/registrations'
  }
     namespace :administrators do
       resources :logs
       resources :dashboard ,:only =>  [:index]
     end
  # You can have the root of your site routed with "root"
   root 'top#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/administrator_log.rb
class AdministratorLog < ActiveRecord::Base
end

app/models/administrators.rb
module Administrators
  def self.table_name_prefix
    'administrators_'
  end
end

app/models/administrators/log.rb
class AdministratorLog < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/log_detail.rb
class LogDetail < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  establish_connection(:development_iqube) if Rails.env.development?
  establish_connection(:production_iqube) if Rails.env.production?
end

app/controllers/administrators/dashboard_controller.rb
class Administrators::DashboardController < AdministratorsController
  def index

  end
end

app/controllers/administrators/logs_controller.rb
class Administrators::LogsController < AdministratorsController
  before_action :set_administrators_log, only: [:show, :edit, :update, :destroy]

  # GET /administrators/logs
  # GET /administrators/logs.json
  def index
    @administrators_log = AdministratorLog.all
  end

  # GET /administrators/logs/1
  # GET /administrators/logs/1.json
  def show
  end

  # GET /administrators/logs/new
  def new
    @administrators_log = AdministratorLog.new
  end

  # GET /administrators/logs/1/edit
  def edit
  end

  # POST /administrators/logs
  # POST /administrators/logs.json
  def create
    @administrators_log = AdministratorLog.new(administrators_log_params)

    respond_to do |format|
      if @administrators_log.save
        format.html { redirect_to @administrators_log, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @administrators_log }
      else
        format.html { render :new }
        format.json { render json: @administrators_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/logs/1
  # PATCH/PUT /administrators/logs/1.json
  def update
    respond_to do |format|
      if @administrators_log.update(administrators_log_params)
        format.html { redirect_to @administrators_log, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrators_log }
      else
        format.html { render :edit }
        format.json { render json: @administrators_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/logs/1
  # DELETE /administrators/logs/1.json
  def destroy
    @administrators_log.destroy
    respond_to do |format|
      format.html { redirect_to administrators_log_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrators_log
      @administrators_log = AdministratorLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrators_log_params
      params[:administrators_log]
    end
end

app/controllers/administrators/passwords_controller.rb
class Administrators::PasswordsController < Devise::PasswordsController
  layout "login"
end

app/controllers/administrators/registrations_controller.rb
class Administrators::RegistrationsController < Devise::RegistrationsController
  layout "login"
end

app/controllers/administrators/sessions_controller.rb
class Administrators::SessionsController < Devise::SessionsController
  layout "login"
  def after_sign_in_path_for(resource)
    administrators_dashboard_index_path
  end
  def after_sign_out_path_for(resource)
    new_administrator_session_path
  end
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :authenticate_administrator! ,:set_administrator


  private
  def set_administrator
    @administrator ||= current_administrator
  end

  def administrator_params
    params.require(:administrator).permit(:name, :email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    redirect_to new_administrator_session_path
  end
end

app/helpers/administrators/dashboard_helper.rb
module Administrators::DashboardHelper
end

app/helpers/administrators/logs_helper.rb
module Administrators::LogsHelper
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/administrators/_form.html.erb
<%= form_for @administrator, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label' %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label' %>
    <%= f.text_field :email, :class => 'form-control' %>
  </div>
    <div class="form-group">
      <%= f.label :password, :class => 'control-label' %>
      <%= f.text_field :password, :class => 'form-control' %>
    </div>
  <div class="form-group">
    <%= f.label :password_confirmation, :class => 'control-label' %>
    <%= f.text_field :password_confirmation, :class => 'form-control' %>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                administrators_path, :class => 'btn' %>
  </div>
<% end %>

app/views/administrators/dashboard/index.html.erb
aaa

app/views/administrators/edit.html.erb
<%- model_class = Administrator -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/administrators/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<%- model_class = Administrator -%>
  <div class="page-header" id="banner">
    <div class="row">
        <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
    </div>
  </div>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= link_to administrator.id, administrator_path(administrator) %></td>
        <td><%= administrator.name %></td>
        <td><%= administrator.email %></td>
        <td><%=l administrator.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_administrator_path(administrator), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.update_password', :default => t("helpers.links.update_password")),
                      edit_administrator_path(administrator), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      administrator_path(administrator),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_administrator_path,
            :class => 'btn btn-primary' %>

app/views/administrators/logs/_form.html.erb
<%= form_for(@administrators_log) do |f| %>
  <% if @administrators_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@administrators_log.errors.count, "error") %> prohibited this administrators_log from being saved:</h2>

      <ul>
      <% @administrators_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/administrators/logs/edit.html.erb
<h1>Editing administrators_log</h1>

<%= render 'form' %>

<%= link_to 'Show', @administrators_log %> |
<%= link_to 'Back', administrators_log_path %>

app/views/administrators/logs/index.html.erb
<h1>Listing administrators_log</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administrators_log.each do |administrators_log| %>
      <tr>
        <td><%= link_to 'Show', administrators_log %></td>
        <td><%= link_to 'Edit', edit_administrators_log_path(administrators_log) %></td>
        <td><%= link_to 'Destroy', administrators_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_administrators_log_path %>

app/views/administrators/logs/new.html.erb
<h1>New administrators_log</h1>

<%= render 'form' %>

<%= link_to 'Back', administrators_log_path %>

app/views/administrators/logs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_administrators_log_path(@administrators_log) %> |
<%= link_to 'Back', administrators_log_path %>

app/views/administrators/new.html.erb
<%- model_class = Administrator -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/administrators/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/administrators/show.html.erb
<%- model_class = Administrator -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @administrator.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @administrator.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @administrator.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_token) %>:</strong></dt>
  <dd><%= @administrator.reset_password_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_sent_at) %>:</strong></dt>
  <dd><%= @administrator.reset_password_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @administrator.remember_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sign_in_count) %>:</strong></dt>
  <dd><%= @administrator.sign_in_count %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
  <dd><%= @administrator.current_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @administrator.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
  <dd><%= @administrator.current_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
  <dd><%= @administrator.last_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:confirmation_token) %>:</strong></dt>
  <dd><%= @administrator.confirmation_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:confirmed_at) %>:</strong></dt>
  <dd><%= @administrator.confirmed_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:confirmation_sent_at) %>:</strong></dt>
  <dd><%= @administrator.confirmation_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unconfirmed_email) %>:</strong></dt>
  <dd><%= @administrator.unconfirmed_email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:failed_attempts) %>:</strong></dt>
  <dd><%= @administrator.failed_attempts %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unlock_token) %>:</strong></dt>
  <dd><%= @administrator.unlock_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:locked_at) %>:</strong></dt>
  <dd><%= @administrator.locked_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              administrators_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_administrator_path(@administrator), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              administrator_path(@administrator),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "loglog" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <![endif]-->

  <%= stylesheet_link_tag "spacelab", :media => "all" %>

  <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

</head>
<body>
<%= render :partial => "/shared/menu.erb" %>

  <div class="container">
    <div class="page-header" id="banner">
    </div>
    <%= render :partial => "/shared/alert.erb" %>
    <div class="container">
    <%= yield %>
  </div> <!-- /container -->
<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "spacelab" %>
<%= yield(:page_javascript) if content_for?(:page_javascript) %>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "loglog" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <![endif]-->

  <%= stylesheet_link_tag "spacelab", :media => "all" %>

  <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

</head>
<body>
  <div class="container theme-showcase">

    <%= yield %>
  </div> <!-- /container -->
<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "spacelab" %>
<%= yield(:page_javascript) if content_for?(:page_javascript) %>

</body>
</html>

app/views/shared/_alert.erb
<% if notice %>
    <div class="row">
      <div class="col-lg-12">
        <div class="bs-component">
          <div class="alert alert-dismissable alert-info">
            <button type="button" class="close" data-dismiss="info">&times;</button>
            <h4>Information!</h4>
            <p><%= notice %></p>
          </div>
        </div>
      </div>
    </div>
<% end %>
<% if alert %>
    <div class="row">
      <div class="col-lg-12">
        <div class="bs-component">
          <div class="alert alert-dismissable alert-danger">
            <button type="button" class="close" data-dismiss="danger">&times;</button>
            <h4>Warning!</h4>
            <p><%= alert %></p>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/shared/_menu.erb
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">LogLog Administrator</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @administrator.name %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Account", edit_administrators_log_path(@administrator) %></a></li>
          <li class="divider"></li>
          <li><%= link_to "Logout", destroy_administrator_session_path, method: :delete %></li>
        </ul>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>